#!/bin/bash
#
# Copyright © 2012-2013 Sergio Arroutbi Braojos <sarroutbi@gmail.com>
# 
# Permission to use, copy, modify, and/or distribute this software 
# for any purpose with or without fee is hereby granted, provided that 
# the above copyright notice and this permission notice appear in all copies.
# 
# THE SOFTWARE IS PROVIDED “AS IS” AND THE AUTHOR DISCLAIMS ALL WARRANTIES 
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY 
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, 
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM 
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, 
# NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE 
# OR PERFORMANCE OF THIS SOFTWARE.
#
# This script gets all the bicycles from
# Biciescapa store !
#
URL="www.sanferbike.com"
ONLY_DOMAIN="sanferbike.com"
MAX_TRIES=10
MAX_TIMEOUT=10
MAX_BIKES_PAGE=200

function get_page()
{
  BASE_URL="$1"
  PAGES="$2"
  if [ "${PAGES}" = "" ];
  then
    wget --tries=${MAX_TRIES} --timeout=${MAX_TIMEOUT} "${BASE_URL}" 
  else
    for page in ${PAGES};
    do
      wget --tries=${MAX_TRIES} --timeout=${MAX_TIMEOUT} "${BASE_URL}${page}" 
    done 
  fi
}

get_page "${URL}/tiendaonline/164-lap-carretera-hombre?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/165-lap-carretera-mujer?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/166-lap-montana-hombre?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/167-lap-montana-mujer?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/168-bicicletas-hibridas-mujeres?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/169-lap-urbanas?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/171-x-country-maraton?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/172-all-mountain-enduro?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/173-over-ride-montana-lapierre?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/174-orbea-montana-hombre?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/176-orbea-carretera-hombre-2013?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/177-orbea-carretera-mujer-2013?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/178-orbea-hibridas-2013?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/179-orbea-infantil-2013?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/180-bicicletas-orbea-urbanas-2013?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/182-bicicletas-orbea-2013-maraton?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/183-bicicletas-orbea-2013-enduro?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/186-hibridas-hombres?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/187-hibridas-mujeres?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/189-cannondale-2013?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/191-bmc-2013-montana-hombre?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/192-x-country-maraton-2013?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/193-bmc-2013-carretera?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/195-all-mountain?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/197-bmc-2013-urbanas-fitness?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/198-lapierre-bmx-dirt?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/199-bicicletas-urbanas-hombres?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/200-mujeres?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/201-orbea-montana-mujer?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/203-bicicleta-montana-hombre?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/204-montana-mujer?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/205-carretera?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/206-urbanas?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/207-sport-maraton?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/208-all-enduro-cannondale?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/209-over-mountain?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/213-giant-carretera-hombre?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/214-bicicletas-montana-hombre?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/215-x-country-maraton?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/216-bicicletas-descenso-giant?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/217-bicicletas-montana-hombre-over-mountain?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/218-bicicletas-ciudad-urbanas-hombres?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/220-bicicletas-hibridas-madrid?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/222-bicicletas-ciudad-urbanas-giant?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/223-bicicletas-ciudad-urbanas-mujeres?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/225-dahon-calidad-plegables?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/226-carretera-mujer-2013?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/227-competicion?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/228-rendimiento?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/229-ciclo-cross?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/230-sport?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/231-fitness?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/232-bicicletas-ciudad-urbanas-mujeres?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/233-bici-mujer-cross?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/234-orca?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/235-aqua?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/236-onix?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/237-terra-bicicletas-ciclocross?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/238-ordu?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/239-bicicleta-orca-mujer?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/240-bicicleta-aqua-mujer?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/241-bicicletas-orbea-montana?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/242-bicicletas-orbea-montana?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/243-bicicletas-sport-orbea?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/245-bicicletas-ciudad-urbanas-orbea?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/247-bicicletas-ciudad-urbanas-orbea-carpe?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/249-bicicletas-ciudad-urbanas-orbea-dude?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/251-bicicletas-ciudad-urbanas-orbea-boulevard?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/255-bicicletas-carretera-fitness-orbea?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/257-bicicletas-giant-montana-mujer?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/258-ruedas-29?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/259-bicis-29?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/263-scalpel?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/264-rz?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/265-trail?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/266-b?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/267-caad?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/268-supersix?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/269-shinapse?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/270-slice?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/274-bicicletas-29er?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/275-pro-race?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/276-x-control?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/277-x-flow?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/278-raid?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/279-xr?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/280-zesty?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/281-spicy?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/286-b?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/287-anthem?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/288-bicicleta-montana-maraton?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/289-trance?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/290-talon?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/291-revel?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/292-b?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/293-team-elite?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/294-foustroke?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/295-sport-elite?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/296-speed-fox?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/297-timemachine?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/298-teammachine?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/299-roadracer?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/300-racemachine?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/301-impec?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/302-granfondo?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/303-trance-29?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/304-reign?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/305-bicis-electricas?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/306-defy?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/307-tcr?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/308-trinity?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/309-flash?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/310-superx?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/311-plegables-orbea?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/318-ofertas-2012-bicis-montana?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/319-carretera-road-ofertas-bicicletas?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/320-ofertas-2013-road?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/321-ofertas-2013-mtb?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/322-ofertas-2011-bicis-carretera?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/323-bicis-montana-2011-en-oferta?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/325-tm?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/326-tmr?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/331-plegables?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/43-bicicletas?n=${MAX_BIKES_PAGE}"

# MTB-DOUBLE
get_page "${URL}/tiendaonline/474-scalpel-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/475-rush-cannondale-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/455-over-mountain-cannondale-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/497-xc?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/498-xr?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/500-zt?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/501-sp?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/494-big-mountain-lapierre?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/418-occam-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/390-nuevas-orbea-oiz-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/530-giant-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/544-all?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/379-trailfox-montana-bmc?n=${MAX_BIKES_PAGE}"

# MTB-FIX
get_page "${URL}/tiendaonline/477-bicicletas-flash?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/476-trail-cannondale-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/495-pro?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/496-ra?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/393-nuevas-orbea-alma-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/395-nuevas-orbea-sport-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/385-nuevas-orbea-mx-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/533-giant-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/543-revel-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/547-x?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/378-sportelite-montana-bmc?n=${MAX_BIKES_PAGE}"

# MTB-27'5
get_page "${URL}/tiendaonline/508-bi?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/484-bicis-27?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/483-bi?n=${MAX_BIKES_PAGE}"

# MTB-29
get_page "${URL}/tiendaonline/472-bicis-29-cannondale-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/499-l29?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/481-b?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/375-bmc-montana-foustroke?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/374-bmc-montana-teamelite?n=${MAX_BIKES_PAGE}"

# MTB-WOMAN
get_page "${URL}/tiendaonline/465-montana-mujer-cannondale-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/487-montana-mujer-lap?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/482-montana-mujer?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/538-m?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/518-hibridas-mujeres?n=${MAX_BIKES_PAGE}"

# ROAD
get_page "${URL}/tiendaonline/462-carretera-hombre-cannondale-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/488-bicis-carretera-hombre-lapierre-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/406-orbea-road?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/539-car?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/365-nuevas-bmc-carretera?n=${MAX_BIKES_PAGE}"

# ROAD-WOMAN
get_page "${URL}/tiendaonline/458-carretera-mujer-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/489-cml?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/485-carretera-mujer-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/540-car?n=${MAX_BIKES_PAGE}"

# URBAN
get_page "${URL}/tiendaonline/478-urbanas-cannondale-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/527-electricas-cannondale?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/490-ul?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/412-urban?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/550-h?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/541-e?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/517-brompton-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/225-dahon-calidad-plegables?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/528-bicis-plegables?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/305-bicis-electricas?n=${MAX_BIKES_PAGE}"

# KIDS
get_page "${URL}/tiendaonline/479-cannondale-para-ninos?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/507-n?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/405-nuevas-orbea-mx-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/536-ninos?n=${MAX_BIKES_PAGE}"

# 2014 REVIEW
get_page "${URL}/tiendaonline/464-bicicletas-2014-cannondale-montana?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/11058-bicicletas-cannondale-trigger-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/11059-bicicletas-cannondale-jekyll-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/463-sport-maraton-cannondale-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/466-caad-cannondale-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/468-cannondale-supersix-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/457-synapse-cannondale?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/470-superx-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/469-slice-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/524-bad-boys?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/525-tesoro?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/526-quick?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/480-tandem-cannondale?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/450-bicicletas-2014-lapierre?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/486-montana-hombre-lap?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/492-xml?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/493-aml?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/512-bi?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/513-bi?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/502-au?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/503-sen?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/504-xel?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/505-cc?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/506-sha?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/380-nuevas-bicicletas-orbea-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/409-orbea-mtb-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/388-nuevas-orbea-alma-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/389-alma-27?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/387-nuevas-orbea-alma-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/381-aqua-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/382-orca-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/383-nuevas-orbea-avant-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/384-nuevas-orbea-ordu-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/11063-avant-dama-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/11064-orca-dama-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/394-nuevas-orbea-boulevard-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/401-nuevas-orbea-rude-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/447-fixie-carpe-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/448-dude?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/403-nuevas-orbea-folding-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/410-all-use?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/398-nuevas-orbea-confort-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/397-nuevas-orbea-confort-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/446-travel-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/521-comfort-28-dama-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/522-comfort-26-dama-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/523-travel-dama-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/515-giant-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/537-mo?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/531-giant-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/542-s?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/545-reign-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/546-trance-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/534-giant-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/548-trinity-14?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/549-defy-14?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/535-giant-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/364-catalogo-bicicletas-bmc-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/371-bmc-timemachine-carretera?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/372-bmc-road-trackmachine?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/366-nuevas-bicis-bmc?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/370-bicis-grandfondo-carretera-bmc?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/369-bicicletas-2014-bmc-teammachine?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/373-nuevas-bmc-montana?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/551-trailfox-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/509-sport-maraton?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/511-bi?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/376-urbanas-bmc?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/377-urbanas-bmc?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/367-cuadros-bmc-nuevos-2014?n=${MAX_BIKES_PAGE}"
get_page "${URL}/tiendaonline/348-bicicletas-2014-cannondale?n=${MAX_BIKES_PAGE}"